gsap.from("#img1",{
    opacity:0,
    delay:0.5,
    duration:1,
    y:60
})
gsap.from("#img2",{
    opacity:0,
    delay:0.5,
    duration:1,
    x:60
})
gsap.from("#img3",{
    opacity:0,
    delay:0.5,
    duration:1,
    y:-60 
})
gsap.from("#main",{
    opacity:0,
    delay:0.5,
    duration:1,
})